# Generated by Django 5.0.6 on 2024-08-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('numment', models.AutoField(db_column='NumMent', primary_key=True, serialize=False)),
                ('mention', models.CharField(blank=True, db_column='Mention', max_length=51, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'mention',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('matricule', models.AutoField(db_column='Matricule', primary_key=True, serialize=False)),
                ('nomprof', models.CharField(blank=True, db_column='NomProf', max_length=50, null=True)),
                ('prenomprof', models.CharField(blank=True, db_column='PrenomProf', max_length=50, null=True)),
                ('telprof', models.IntegerField(blank=True, db_column='TelProf', null=True)),
                ('specialite', models.CharField(blank=True, db_column='Specialite', max_length=50, null=True)),
            ],
            options={
                'db_table': 'prof',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('numsalle', models.AutoField(primary_key=True, serialize=False)),
                ('nomsalle', models.IntegerField(blank=True, db_column='Nomsalle', null=True)),
            ],
            options={
                'db_table': 'salle',
                'managed': False,
            },
        ),
    ]
